env:
  commonjs: true
  es2021: true
  node: true
extends:
  - google
  - eslint:recommended
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 12
rules:
  arrow-body-style:
    - error
    - as-needed
    - requireReturnForObjectLiteral: true
  camelcase:
    - error
  no-prototype-builtins:
    - warn
  guard-for-in:
    - warn
  prettier/prettier:
    - error
  quotes:
    - error
    - backtick
